import { TractoRoute, WorkForm, TractoBranches } from '@/components'

//TODO: agregar todas las metadatas faltantes
export const metadata = {
  title: 'Institucional',
  description: 'Generated by create next app',
}

export default function Institucional() {
  return (
    <div className="mw-950">
      <main>
        <h1 className="h1">Orgullosos de nuestro crecimiento, compartimos contigo nuestro recorrido.</h1>
        <TractoRoute />
      </main>
      <section>
        <h2 className="h1">Se parte de este gran equipo humano.</h2>
        <WorkForm />
      </section>
      <section>
        <h2 className="h1">Elegí la que esté más cerca y visítanos, contamos con cobertura total.</h2>
        <TractoBranches />
      </section>
    </div>
  )
}
