export const metadata = {
    title: 'Institucional',
    description: 'Generated by create next app',
  }
  
  export default function Institucional() {
    return (
      <main>
        <h1>Institucional</h1>
      </main>
    )
  }
  