import { TractoRoute, WorkForm, TractoBranches } from '@/components'

export const metadata = {
  //title y description
  title: 'Institucional',
  description: 'Generated by create next app', //TODO: cambiar el title y description

  //favicon
  /*icons: {
    icon: '/images/favicon.png',
    shortcut: '/images/favicon.png',
    apple: '/images/favicon.png',
    other: {
      rel: 'apple-touch-icon-precomposed',
      url: '/images/favicon.png',
    },
  },*///TODO: cambiar el contenido para favicon

  //open graph
  openGraph: {
    title: 'Tracto Agro Vial',
    description: 'Tracto Agro Vial',
    url: 'https://tractoagrovial.com',
    siteName: 'Tracto Agro Vial',
    images: [
      {
        url: '/images/favicon.png',
        width: 800,
        height: 600,
      },
      {
        url: '/images/favicon.png',
        width: 1800,
        height: 1600,
        alt: 'Tracto Agro Vial',
      },
    ],
    locale: 'es_AR',
    type: 'website',
  }, //TODO: cambiar el contenido para open graph

  //twitter
  twitter: {
    card: 'summary_large_image',
    title: 'Tracto Agro Vial',
    description: 'Tracto Agro Vial',
    siteId: '1467726470533754880',
    creator: '@tractoagrovial',
    creatorId: '1467726470533754880',
    images: ['/images/favicon.png'], //TODO: cambiar el contenido para twitter
  },

  //category 
  category: 'technology',//TODO: cambiar la categoria

}

export default function Institucional() {
  return (
    <div className="mw-950">
      <main id='route'>
        <h1 className="h1">Orgullosos de nuestro crecimiento, compartimos contigo nuestro recorrido.</h1>
        <TractoRoute />
      </main>
      <section id='workHere'>
        <h2 className="h1">Se parte de este gran equipo humano.</h2>
        <WorkForm />
      </section>
      <section id='branches'>
        <h2 className="h1">Elegí la que esté más cerca y visítanos, contamos con cobertura total.</h2>
        <TractoBranches />
      </section>
    </div>
  )
}
