export const metadata = {
  title: 'Inicio',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main className="mw-950">
      <h1>Inicio</h1>
    </main>
  )
}
