import { ContactForm } from "@/components"

export const metadata = {
  title: 'PosVenta',
  description: 'Generated by create next app',
}

export default function PosVenta() {
  return (
    <main className="mw-950">
      <h1 className="h1">Extendé la vida de tus máquinas, agenda un servicio.</h1>
      <ContactForm />
    </main>
  )
}
